server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: qweasdzxc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signer-key: "1kGEGfShx74J0l0dwaYwEbcgqN9QWBSTi4HWuJUf6Kyn4oSSgF9CFYXx7A0hCii/"
  valid-duration: 60 # in second
  refreshable-duration: 120 # second
